      async function loadStudyCatalog(){if(studyCatalogRequested)return;studyCatalogRequested=true;try{const response=await fetch('/api/studies-catalog');if(!response.ok)throw new Error('HTTP '+response.status);studyServerCatalog=await response.json()}catch(error){studyServerCatalog={sectors:[],error:error.message}}if(page==='studies')render()}
      function studyControls(){return '<div class="study-toolbar"><label for="study-sector-select">Target Sector</label><select id="study-sector-select"><option value="">Selected Issuers / LQ45</option>'+(studyServerCatalog?.sectors||[]).map(s=>'<option value="'+escapeHTML(s.value)+'" '+(s.value===studySector?'selected':'')+'>'+escapeHTML(s.value)+' · '+s.members.length+' emiten</option>').join('')+'</select><button class="action primary" data-action="run-all-studies" '+(!studyPanels.length?'disabled':'')+'>Run All Panels</button><span class="study-small-note">Local Computation · No LLM</span>'+(studyServerCatalog?.error?'<span role="alert">API lokal belum tersedia: '+escapeHTML(studyServerCatalog.error)+'</span>':'')+'</div>'}
      function studyPanelMarkup(panel,index){const state=studyRunner.states[panel.id]||{status:'NOT_RUN'};const body='<div class="study-run-controls"><button class="action primary" data-action="run-study-panel" data-panel-id="'+escapeHTML(panel.id)+'" '+(state.status==='RUNNING'?'disabled':'')+'>Run</button><button class="action" data-action="cancel-study-panel" data-panel-id="'+escapeHTML(panel.id)+'" '+(state.status!=='RUNNING'?'disabled':'')+'>Cancel</button></div>'+(panel.type==='custom_engineering'?'<div class="study-config-row"><label>Field <select data-action="custom-field">'+['close','volume','foreign_net_flow'].map(f=>'<option '+(f===studyCustomField?'selected':'')+'>'+f+'</option>').join('')+'</select></label><label>Transform <select data-action="custom-transform">'+['difference','pct_change','rolling_mean','rolling_std','robust_z'].map(t=>'<option '+(t===studyCustomTransform?'selected':'')+'>'+t+'</option>').join('')+'</select></label></div>':'')+'<div class="study-output" role="status" aria-live="polite">'+(['STALE','RUNNING','CANCELLED','ERROR'].includes(state.status)?'<p>'+escapeHTML(state.status)+' · '+escapeHTML(state.error||'Jalankan kembali untuk input yang aktif.')+'</p>':StudiesUI.renderResult(state.result,panel.showAll?Infinity:100))+'</div>';return studyPanelLayoutMarkup(panel,index).replace('<span class="state warn">NOT RUN</span>','<span class="state warn">'+escapeHTML(state.status)+'</span>').replace(/<div class="study-window-body">[\s\S]*?(?=<button class="study-resize-grip")/,'<div class="study-window-body">'+body+'</div>')}
      try{const stored=JSON.parse(localStorage.getItem('idxel-study-layouts')||'[]');if(Array.isArray(stored))studySaved=stored}catch(_e){}
      function escapeHTML(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]})}
      function studyDetails(type){const data={
        price_risk:{title:'Price & volatility',source:'Daily OHLCV • 45/45 ticker • akhir 24 Sep 2026',fields:'Return • realized volatility • downside deviation • drawdown • ATR',formula:'rolling_std(return, '+studyWindow+' sesi) × √252; max drawdown dari kurva indeks harga',caveat:'Histori mengikuti ketersediaan per ticker; AADI mulai 5 Des 2024.'},
        trend_momentum:{title:'Trend & momentum',source:'Daily OHLCV • periode per ticker',fields:'SMA/EMA distance • slope • RSI • MACD • volume change',formula:'close / MA(n) − 1; seluruh indikator memakai bar harian yang sudah selesai',caveat:'Deskriptif; kondisi teknikal bukan sinyal atau probabilitas.'},
        liquidity_proxy:{title:'Liquidity & downside proxy',source:'Daily OHLCV • proxy, bukan order book',fields:'Turnover • volume percentile • gap frequency • downside moves',formula:'nilai transaksi dan distribusi OHLCV per jendela yang dipilih',caveat:'Bukan spread, depth, ARB, atau prediksi suspensi.'},
        quality_valuation:{title:'Valuation & quality',source:'Company report 45/45 • field coverage berbeda',fields:'Valuasi • profitabilitas • growth • leverage • cash flow',formula:'peer median / robust percentile hanya pada metrik dan peer yang sebanding',caveat:'Forward P/E 37/45; forecast 38/45. Bank memiliki field khusus; report price 25 Sep vs daily 24 Sep.'},
        fragility:{title:'Financial fragility',source:'Company report • histori tahunan 3–8 tahun',fields:'Kas • leverage • margin • profitabilitas • cash-flow direction',formula:'perubahan periode laporan dan flags yang memiliki definisi/unit cocok',caveat:'Kuartalan opsional. Field generik kosong untuk lima bank bukan otomatis error.'},
        issuer_flow:{title:'Issuer flow & price response',source:'Daily OHLCV + foreign flow (mulai 2 Jan 2025) + arsip broker issuer-level yang tersedia',fields:'Net foreign flow • broker activity bila snapshot issuer-level cocok • return sesudah observasi',formula:'selaraskan tanggal observasi; abnormality hanya terhadap baseline historis yang cukup',caveat:'Cakupan dan definisi flow berbeda. Broker flow tidak mengidentifikasi pemilik/niat; unusual-flow LQ45 agregat belum tersedia.'},
        event_timeline:{title:'Event & governance timeline',source:'Filings 341 • news 145 pada jendela tertentu • actions 757 • suspensi verified',fields:'Filings • news • corporate actions • riwayat suspensi • legal references',formula:'urutkan event-time dan publication-time; deduplikasi berdasarkan sumber/id',caveat:'News bukan arsip kontinu; status suspensi adalah riwayat, bukan prediksi.'},
        market_context:{title:'IHSG context & regime',source:'IHSG lokal • 708 observasi, 25 Sep 2023–24 Sep 2026; OHLCV emiten harian',fields:'Return relatif terhadap IHSG • posisi IHSG vs SMA 50/200 • volatilitas 20 sesi dan persentil rolling',formula:'tren: close dan SMA50 dibanding SMA200; volatilitas: std return 20 sesi × √252',caveat:'Baseline teknikal deskriptif, bukan regime tervalidasi/forecast. Selaraskan tanggal; LQ45 bukan pengganti IHSG.'},
        market_breadth:{title:'Market breadth · LQ45',source:'OHLCV harian emiten + indeks LQ45 lokal untuk tanggal acuan',fields:'Jumlah advancers/decliners/unchanged • proporsi di atas SMA20/SMA50 • coverage',formula:'return close-to-close pada tanggal indeks bersama; SMA per emiten pada histori yang tersedia',caveat:'Universe snapshot LQ45 saat ini, bukan seluruh IDX atau membership historis. Hasil ditahan bila coverage <70%.'},
        capm_benchmark:{title:'CAPM · IHSG benchmark',source:'IHSG lokal • return historis + asumsi target ATH 9.174 • risk-free input manual',fields:'Beta portofolio • premi pasar historis • premi skenario ATH • hurdle CAPM masing-masing',formula:'CAPM = Rf + β × (Rm − Rf); historis memakai IHSG pada sampel portofolio, ATH memakai upside kumulatif',caveat:'ATH bukan ramalan dan horizon ATH tidak ditentukan; skenario ATH tidak diannualisasi. RF manual 7,129% adalah asumsi, bukan feed obligasi.'},
        portfolio_risk:{title:'Portfolio risk ratios',source:'Daily close LQ45 • bobot pilihan Portfolio Lab • risk-free manual untuk Sharpe',fields:'Sharpe • Sortino • Calmar • maximum drawdown • lintasan drawdown',formula:'annualisasi sesuai metrik; Sortino memakai downside deviation, Calmar memakai CAGR / |MDD|',caveat:'In-sample price return, bukan kinerja ke depan. Risk-free adalah asumsi manual; dividen/aksi belum terverifikasi.'},
        factor_exposure:{title:'Factor characteristics & exposure',source:'Snapshot Factor Zoo Sectors.app lokal + bobot target Portfolio Lab',fields:'Skor Value • Quality • Momentum • Low Volatility; exposure berbobot dan coverage bobot',formula:'rata-rata skor yang tersedia × bobot target, dinormalisasi pada bobot dengan skor',caveat:'Karakteristik lintas-seksi deskriptif, bukan return factor atau model Fama–French; tidak mengubah optimizer.'},
        issuer_compare:{title:'Compare issuers',source:'Pilih ticker dan periode yang dapat dibandingkan',fields:'Peer valuation • financial metrics • price/flow/event context',formula:'tampilkan metrik berdampingan dengan coverage dan common period',caveat:'Tahan perbandingan lintas sektor atau beda definisi yang tidak sepadan.'},
        event_outcomes:{title:'Event study & outcomes',source:'Daily + event timestamp + benchmark bila tersedia',fields:'Forward return • MAE/MFE • sample • baseline delta • interval',formula:'definisikan event, horizon, tanggal masuk, baseline, dan split waktu',caveat:'Belum ada hasil tervalidasi; universe saat ini berisiko survivorship bias.'},
        custom_engineering:{title:'Custom feature engineering',source:'Allowlist field lokal dengan unit dan availability timestamp',fields:'Lag • perubahan • rolling mean/std • ratio • rank/robust z-score',formula:'field_A / field_B hanya jika unit, denominator, periode, dan applicability cocok',caveat:'Tidak menerima kode bebas. Preview formula dan missingness sebelum menambah panel.'},
        evidence_trace:{title:'Evidence & methodology',source:'Manifest, metadata, ledger, hash, dan snapshots',fields:'Input IDs • coverage • source • formula/model version • status',formula:'trace setiap hasil ke snapshot dan versi transformasi',caveat:'Input FOUND tidak sama dengan analisis yang sudah dihitung atau tervalidasi.'}
      };return data[type]||data.evidence_trace}
      let studyWorldW=2600,studyWorldH=1800,studyZoom=1;
      function makeStudyPanel(type,index){const detail=studyDetails(type);return {id:'study-'+Date.now()+'-'+index+'-'+Math.random().toString(36).slice(2,7),type:type,x:16+(index%2)*660,y:20+Math.floor(index/2)*460,w:620,h:420,title:detail.title}}
      function studyPanelLayoutMarkup(panel,index){
        const d=studyDetails(panel.type),left=panel.x==null?16+(index%2)*660:panel.x,top=panel.y==null?20+Math.floor(index/2)*270:panel.y,width=panel.w||620,height=panel.h||380,targets=studyTargets.length?studyTargets.join(' · '):'LQ45 universe';
        const custom=panel.type==='custom_engineering'?'<div class="study-config-row"><label class="study-small-note" for="custom-field-'+escapeHTML(panel.id)+'">Field</label><select id="custom-field-'+escapeHTML(panel.id)+'" data-action="custom-field"><option value="close" '+(studyCustomField==='close'?'selected':'')+'>Daily close</option><option value="volume" '+(studyCustomField==='volume'?'selected':'')+'>Daily volume</option><option value="foreign_net_flow" '+(studyCustomField==='foreign_net_flow'?'selected':'')+'>Foreign net flow*</option><option value="issuer_broker_net_flow" '+(studyCustomField==='issuer_broker_net_flow'?'selected':'')+'>Broker net flow per issuer*</option><option value="operating_cash_flow" '+(studyCustomField==='operating_cash_flow'?'selected':'')+'>Operating cash flow*</option></select><label class="study-small-note" for="custom-transform-'+escapeHTML(panel.id)+'">Transform</label><select id="custom-transform-'+escapeHTML(panel.id)+'" data-action="custom-transform"><option value="rolling_mean" '+(studyCustomTransform==='rolling_mean'?'selected':'')+'>Rolling mean</option><option value="rolling_std" '+(studyCustomTransform==='rolling_std'?'selected':'')+'>Rolling std</option><option value="pct_change" '+(studyCustomTransform==='pct_change'?'selected':'')+'>Percent change</option><option value="difference" '+(studyCustomTransform==='difference'?'selected':'')+'>Difference</option><option value="robust_z" '+(studyCustomTransform==='robust_z'?'selected':'')+'>Robust z-score</option></select><button class="action" data-action="preview-custom-formula">Preview formula</button><span class="study-small-note">*hanya bila coverage field tersedia; bukan kode bebas.</span></div>':'';
        const formula=panel.type==='custom_engineering'?studyCustomTransform+'('+studyCustomField+', '+studyWindow+' sesi)':d.formula;
        return '<article class="study-window" data-study-panel="'+escapeHTML(panel.id)+'" style="left:'+left+'px;top:'+top+'px;width:'+width+'px;height:'+height+'px"><header class="study-window-head" data-drag-handle="true"><strong>'+escapeHTML(panel.title||d.title)+'</strong><span class="state warn">NOT RUN</span><div class="study-panel-actions"><button class="action ghost" data-action="move-study-panel" data-panel-id="'+escapeHTML(panel.id)+'" data-direction="left" aria-label="Geser panel ke kiri">←</button><button class="action ghost" data-action="move-study-panel" data-panel-id="'+escapeHTML(panel.id)+'" data-direction="right" aria-label="Geser panel ke kanan">→</button><button class="action ghost" data-action="move-study-panel" data-panel-id="'+escapeHTML(panel.id)+'" data-direction="up" aria-label="Geser panel ke atas">↑</button><button class="action ghost" data-action="move-study-panel" data-panel-id="'+escapeHTML(panel.id)+'" data-direction="down" aria-label="Geser panel ke bawah">↓</button><button class="action ghost" data-action="resize-study-panel" data-panel-id="'+escapeHTML(panel.id)+'" aria-label="Ubah ukuran panel">↗</button><button class="action ghost" data-action="remove-study-panel" data-panel-id="'+escapeHTML(panel.id)+'" aria-label="Tutup window">×</button></div></header><div class="study-window-body"><div class="study-status-row"><span class="study-chip">Target: '+escapeHTML(targets)+'</span><span class="study-chip">As of 24 Sep 2026</span></div><div class="study-placeholder-label">Metrik yang akan dihitung</div><p class="study-formula">'+escapeHTML(d.fields)+'</p>'+custom+'<div class="study-metric-row"><div class="study-metric-cell"><b>Output</b><span>Belum dihitung</span></div><div class="study-metric-cell"><b>Formula</b><span>Versi belum dijalankan</span></div></div><div class="study-not-run"><b>Panel siap dikonfigurasi</b><br>Rancangan ini belum menjalankan pipeline/model dan tidak menampilkan angka ilustratif.</div><p class="study-small-note"><b>Input:</b> '+escapeHTML(d.source)+'<br><b>Formula usulan:</b> '+escapeHTML(formula)+'<br><b>Batas:</b> '+escapeHTML(d.caveat)+'</p></div><button class="study-resize-grip" data-resize-handle="true" aria-label="Ubah ukuran window"></button></article>'
      }
      function studies(){
        loadStudyCatalog();
        const groups=['ALL','PRICE & RISK','FUNDAMENTAL','FLOW & EVENTS','CONTEXT','BUILD'];
        const catalog=studyCatalog.filter(function(item){return studyGroup==='ALL'||item.group===studyGroup});
        const panels=studyPanels.map(studyPanelMarkup).join('');
        const saved=studySaved.map(function(item){return '<div class="study-saved-item"><span>'+escapeHTML(item.name)+'</span><button class="action ghost" data-action="load-study-layout" data-layout-id="'+escapeHTML(item.id)+'">Open</button><button class="action ghost" data-action="delete-study-layout" data-layout-id="'+escapeHTML(item.id)+'" aria-label="Hapus layout '+escapeHTML(item.name)+'">×</button></div>'}).join('');
        return pageHead('Studies','Analisis snapshot lokal · target, formula, hasil dan sumber yang dapat ditelusuri')+studyControls()+
          '<div class="studies-query"><input id="study-query-input" aria-label="Jelaskan analisis yang ingin dibuat" placeholder="Contoh: cek volatilitas BBCA lalu bandingkan dengan BMRI" value="'+escapeHTML(studySearchText)+'"><button class="action primary" data-action="build-study">Create Layout</button></div>'+
          '<div class="study-dock"><details><summary>Feature engineering · '+studyCatalog.length+'</summary><div class="study-dock-popover"><p class="study-hint">Katalog ini memetakan input/analisis yang tersedia. Status input bukan hasil hitung: setiap window tetap NOT RUN sampai pipeline dijalankan.</p><div class="filters">'+groups.map(function(g){return '<button class="filter '+(studyGroup===g?'study-selected':'')+'" data-action="filter-study-catalog" data-group="'+escapeHTML(g)+'">'+escapeHTML(g==='ALL'?'All':g)+'</button>'}).join('')+'</div><div class="study-window-list">'+catalog.map(function(item){const statusClass=item.availability==='TERBATAS'?' limited':item.availability==='RANCANGAN'||item.availability==='BELUM DIUJI'?' planned':'';return '<button class="study-catalog-item" data-action="add-study-panel" data-panel="'+item.id+'"><span>'+escapeHTML(item.name)+'<br><small><b class="study-catalog-status'+statusClass+'">'+escapeHTML(item.availability)+'</b>'+escapeHTML(item.detail)+'</small></span><b aria-hidden="true">+</b></button>'}).join('')+'</div></div></details>'+
          '<div class="study-presets"><span class="study-dock-label">Layout</span><button class="study-recommend" data-action="apply-study-layout" data-layout="volatility">Volatility</button><button class="study-recommend" data-action="apply-study-layout" data-layout="fundamental">Issuer quality</button><button class="study-recommend" data-action="apply-study-layout" data-layout="flow">Flow & events</button><button class="study-recommend" data-action="apply-study-layout" data-layout="risk">Risk ratios</button><button class="study-recommend" data-action="apply-study-layout" data-layout="factors">Factor map</button><button class="study-recommend" data-action="apply-study-layout" data-layout="full">Evidence review</button></div>'+
          '<div class="study-dock-save"><input id="study-layout-name" aria-label="Nama layout dashboard" placeholder="Dashboard name"><button class="action primary" data-action="save-study-layout">Save</button><details class="study-saved-menu"><summary>Dashboard tersimpan ('+studySaved.length+')</summary><div>'+(saved||'<p class="study-empty">Belum ada layout tersimpan di browser ini.</p>')+'</div></details></div></div>'+
          '<section class="study-workspace"><div class="study-toolbar"><label for="study-ticker-input">Target Issuer</label><input id="study-ticker-input" placeholder="Ticker, e.g. BBCA" aria-label="Ticker untuk analisis" style="max-width:145px"><button class="action" data-action="add-study-ticker">Add</button><div class="study-tickers">'+studyTargets.map(function(t){return '<button class="study-ticker-pill" data-action="remove-study-ticker" data-ticker="'+escapeHTML(t)+'" aria-label="Hapus target '+escapeHTML(t)+'">'+escapeHTML(t)+' ×</button>'}).join('')+'</div><label for="study-window-select">Window</label><select id="study-window-select" data-action="select-study-window"><option value="5" '+(studyWindow==='5'?'selected':'')+'>5 sessions</option><option value="20" '+(studyWindow==='20'?'selected':'')+'>20 sessions</option><option value="60" '+(studyWindow==='60'?'selected':'')+'>60 sessions</option><option value="available" '+(studyWindow==='available'?'selected':'')+'>History Available</option></select><div class="study-zoom-controls" aria-label="Kontrol zoom canvas"><button class="action" data-action="study-zoom-out" aria-label="Zoom out">−</button><output id="study-zoom-value">'+Math.round(studyZoom*100)+'%</output><button class="action" data-action="study-zoom-in" aria-label="Zoom in">+</button><button class="action ghost" data-action="study-zoom-reset">Reset</button></div></div>'+
          '<div class="study-canvas" id="study-canvas" aria-label="Canvas riset yang dapat digeser dan di-scroll"><div class="study-world-extent" style="position:relative;width:'+Math.ceil(studyWorldW*studyZoom)+'px;height:'+Math.ceil(studyWorldH*studyZoom)+'px"><div class="study-canvas-world" style="width:'+studyWorldW+'px;height:'+studyWorldH+'px"><div class="study-canvas-world-inner" style="width:'+studyWorldW+'px;height:'+studyWorldH+'px;transform:scale('+studyZoom+')">'+(panels||'<div class="study-empty" style="padding:28px">Canvas masih kosong. Tambahkan panel dari Feature engineering atau buat layout dari kolom di atas.</div>')+'</div></div></div></div></section>'+
          '<p class="study-hint" style="margin:8px 2px">READY berarti hasil dapat dihitung untuk input tersebut, bukan prediksi akurat. Periksa coverage, warm-up, tanggal dan batas setiap metrik.</p>'
      }
      function autoArrangeStudyPanels(){let y=20;studyPanels.forEach(function(p,i){if(!p.w||p.w<100)p.w=620;if(!p.h||p.h<100)p.h=420;p.x=16+(i%2)*660;p.y=y;if(i%2===1)y+=Math.max(p.h,studyPanels[i-1].h)+40});growStudyWorld()}
      function addStudyPanel(type){if(!studyCatalog.some(function(x){return x.id===type}))return;if(!studyPanels.some(function(p){return p.type===type&&p.targetsKey===(studyTargets.join(',')||'LQ45')})){const p=makeStudyPanel(type,studyPanels.length);p.targetsKey=studyTargets.join(',')||'LQ45';studyPanels.push(p);autoArrangeStudyPanels()}render()}
      function addStudyTicker(value){const t=String(value||'').trim().toUpperCase();if(!lq45Tickers.includes(t)){toast('Ticker tidak ditemukan pada snapshot universe LQ45.');return}if(!studyTargets.includes(t))studyTargets.push(t);render()}
      function buildStudyFromQuery(value){const q=String(value||'').trim(),upper=q.toUpperCase();if(!q){toast('Tulis permintaan analisis terlebih dahulu.');return}studyRunner.invalidate();studySearchText=q;const tickers=lq45Tickers.filter(function(t){return new RegExp('(^|[^A-Z0-9])'+t+'([^A-Z0-9]|$)').test(upper)});if(tickers.length){studySector='';studyTargets=tickers;}const requested=[];function match(re,id){if(re.test(q)&&!requested.includes(id))requested.push(id)}match(/volatil|drawdown|risiko|atr|bollinger/i,'price_risk');match(/sharpe|sortino|calmar|rasio risiko|maximum drawdown portofolio/i,'portfolio_risk');match(/capm|beta|premi pasar/i,'capm_benchmark');match(/trend|momentum|rsi|macd|moving average|sma|ema/i,'trend_momentum');match(/breadth|advancer|decliner|partisipasi saham/i,'market_breadth');match(/faktor|factor zoo|exposure faktor/i,'factor_exposure');match(/likuid|turnover|downside|gap/i,'liquidity_proxy');match(/valu|murah|mahal|quality|kualitas|fundamental|peer/i,'quality_valuation');match(/fragil|leverage|utang|arus kas|cash flow/i,'fragility');match(/broker|foreign flow|aliran dana|flow|net buy|net sell/i,'issuer_flow');match(/filing|berita|news|corporate action|dividen|right issue|suspensi|event/i,'event_timeline');match(/ihsg|regime|benchmark|pasar/i,'market_context');match(/banding|compare|komparasi/i,'issuer_compare');match(/event study|outcome|forward return|hasil historis/i,'event_outcomes');match(/custom|feature engineering|rumus sendiri|fitur sendiri/i,'custom_engineering');if(!requested.length){toast('Permintaan belum cocok dengan panel yang tersedia. Coba sebut volatilitas, valuasi, flow, event, bandingkan, atau nama ticker.');return}studyPanels=[];requested.forEach(function(type){const p=makeStudyPanel(type,studyPanels.length);p.targetsKey=studyTargets.join(',')||'LQ45';studyPanels.push(p)});autoArrangeStudyPanels();page='studies';render();studyRunner.runAll(studyPanels);toast('Layout dibuat dari panel allowlist. Perhitungan lokal dimulai sesuai target.')}
      function syncStudyCanvasSize(){const extent=root.querySelector('.study-world-extent'),world=root.querySelector('.study-canvas-world'),inner=root.querySelector('.study-canvas-world-inner');if(extent){extent.style.width=Math.ceil(studyWorldW*studyZoom)+'px';extent.style.height=Math.ceil(studyWorldH*studyZoom)+'px'}if(world){world.style.width=studyWorldW+'px';world.style.height=studyWorldH+'px'}if(inner){inner.style.width=studyWorldW+'px';inner.style.height=studyWorldH+'px';inner.style.transform='scale('+studyZoom+')'}}
      function growStudyWorld(){studyPanels.forEach(function(p){studyWorldW=Math.max(studyWorldW,(p.x||0)+(p.w||620)+900);studyWorldH=Math.max(studyWorldH,(p.y||0)+(p.h||250)+700)});syncStudyCanvasSize()}
      function shiftStudyOrigin(dx,dy){studyPanels.forEach(function(p){p.x=(p.x||0)+dx;p.y=(p.y||0)+dy;const card=root.querySelector('[data-study-panel="'+p.id+'"]');if(card){card.style.left=p.x+'px';card.style.top=p.y+'px'}});studyWorldW+=dx;studyWorldH+=dy;syncStudyCanvasSize()}
      function setStudyZoom(next,anchorX,anchorY){const viewport=root.querySelector('#study-canvas');if(!viewport)return;const old=studyZoom;studyZoom=Math.max(.35,Math.min(2.5,Math.round(next*100)/100));const cx=anchorX==null?viewport.clientWidth/2:anchorX,cy=anchorY==null?viewport.clientHeight/2:anchorY;const worldX=(viewport.scrollLeft+cx)/old,worldY=(viewport.scrollTop+cy)/old;syncStudyCanvasSize();viewport.scrollLeft=Math.max(0,worldX*studyZoom-cx);viewport.scrollTop=Math.max(0,worldY*studyZoom-cy);const output=root.querySelector('#study-zoom-value');if(output)output.value=Math.round(studyZoom*100)+'%'}
      function syncStudyGeometry(){root.querySelectorAll('.study-window').forEach(function(card){const p=studyPanels.find(function(x){return x.id===card.dataset.studyPanel});if(!p)return;p.x=parseFloat(card.style.left)||16;p.y=parseFloat(card.style.top)||20;p.w=card.getBoundingClientRect().width/studyZoom;p.h=card.getBoundingClientRect().height/studyZoom});growStudyWorld()}
      function saveStudyLayout(){syncStudyGeometry();const input=root.querySelector('#study-layout-name'),name=(input&&input.value.trim())||'Dashboard '+new Date().toLocaleString('id-ID');const layout={id:'layout-'+Date.now(),name:name,panels:studyPanels.map(function(p){return Object.assign({},p)}),targets:studyTargets.slice(),window:studyWindow,customField:studyCustomField,customTransform:studyCustomTransform,createdAt:new Date().toISOString()};studySaved.unshift(layout);try{localStorage.setItem('idxel-study-layouts',JSON.stringify(studySaved))}catch(_e){toast('Penyimpanan browser penuh; layout belum disimpan.');return}render();toast('Dashboard disimpan di browser ini.')}
      function applyStudyPreset(key){const presets={volatility:['price_risk','trend_momentum','evidence_trace'],fundamental:['quality_valuation','fragility','issuer_compare','evidence_trace'],flow:['issuer_flow','event_timeline','price_risk','evidence_trace'],risk:['portfolio_risk','market_context','market_breadth','evidence_trace'],factors:['factor_exposure','quality_valuation','trend_momentum','evidence_trace'],full:['price_risk','quality_valuation','issuer_flow','event_timeline','market_context','market_breadth','issuer_compare','evidence_trace']};studyPanels=(presets[key]||[]).map(function(type,i){const p=makeStudyPanel(type,i);p.targetsKey=studyTargets.join(',')||'LQ45';return p});autoArrangeStudyPanels();render()}
